-- Copyright (c) COPYRIGHT-YEAR COPYRIGHT-HOLDER  All rights reserved.
-- $Id$
--
-- Data Definition Language for bOP PetShop Models
--
-- * Tables are named after their models, but have underscores where
--   the case changes.  
-- * Make sure the type sizes match the Model field types--yes, this file 
--   should be generated from the Models...
-- * Don't put any constraints or indices here.  Put them in *-constraints.sql.
--   It makes it much easier to manage the constraints and indices this way.
--

